# Generated by Django 3.0.4 on 2020-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card', models.CharField(default='Visa', max_length=4)),
                ('Card_number', models.IntegerField(default=1234567891234567)),
                ('PIN', models.IntegerField(default=1234)),
                ('CVV', models.IntegerField(default=123)),
                ('Balance', models.IntegerField(default=0)),
                ('Month', models.IntegerField(default=1)),
                ('Year', models.IntegerField(default=2020)),
                ('Name', models.CharField(default='John', max_length=255)),
                ('Address', models.CharField(default='Street', max_length=500)),
                ('Country', models.CharField(default='Usa', max_length=500)),
            ],
        ),
    ]
