# Generated by Django 3.0.4 on 2020-03-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=4)),
                ('Card_Number', models.IntegerField()),
                ('PIN', models.IntegerField()),
                ('CVV', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=500)),
            ],
        ),
    ]
