# Generated by Django 3.0.4 on 2020-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200319_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='id',
        ),
        migrations.AlterField(
            model_name='index',
            name='Card_number',
            field=models.CharField(default='1234 5678 9123 4567', max_length=19, primary_key=True, serialize=False),
        ),
    ]
