# Generated by Django 3.0.4 on 2020-03-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200319_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kartica',
            fields=[
                ('Card_number', models.CharField(default='1234 5678 9123 4567', max_length=19, primary_key=True, serialize=False)),
                ('CVV', models.CharField(default='123', max_length=3)),
                ('Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Verifikacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=4)),
                ('kartica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Kartica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AddField(
            model_name='user',
            name='kartica_usera',
            field=models.ManyToManyField(through='index.Verifikacija', to='index.Kartica'),
        ),
    ]
