# Generated by Django 3.0.4 on 2020-03-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200319_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kartica_usera',
        ),
        migrations.AddField(
            model_name='kartica',
            name='kartica_usera',
            field=models.ManyToManyField(related_name='kartica_usera', through='index.Verifikacija', to='index.User'),
        ),
        migrations.AddField(
            model_name='kartica',
            name='korisnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
